Repository ros2/rosidl_typesupport_fastrtps, pull requests merged in 2019-05, with the labels that each got.

#22 add WString support
  rosidl_typesupport_fastrtps_c/CMakeLists.txt
  rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/wstring_conversion.hpp
  rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_fastrtps_c/src/wstring_conversion.cpp
  rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
  rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/wstring_conversion.hpp
  rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_fastrtps_cpp/src/wstring_conversion.cpp
Labels: enhancement, in review

#24 Ensure boolean initialization in FastRTPS
  rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
Labels: bug, in review

#23 fix size calculation for WStrings
  rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
Labels: bug, in review

#25 hard code size of wchar_t to 4
  rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
Labels: in review

#18 Add message namespace to type support struct
  rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h
  rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h
  rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Labels: in review
