Repository ros2/rosidl_typesupport_fastrtps, pull requests merged in 2020-05, with the labels that each got.

#43 Add tests for wstring conversion routines
  rosidl_typesupport_fastrtps_c/CMakeLists.txt
  rosidl_typesupport_fastrtps_c/package.xml
  rosidl_typesupport_fastrtps_c/test/test_wstring_conversion.cpp
  rosidl_typesupport_fastrtps_c/test/test_wstring_conversion_mem.cpp
  rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
  rosidl_typesupport_fastrtps_cpp/package.xml
  rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion.cpp
  rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion_mem.cpp
Labels: enhancement, in review

#47 Revert "Use modern cmake to fix single typesupport builds (#40)"
  rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake
  rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in
  rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
  rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in
Labels: bug

#46 QD Update Version Stability to stable version
  fastrtps_cmake_module/QUALITY_DECLARATION.md
  rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
  rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Labels: enhancement
